name: Pytest API and UI Tests Run

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4.2.2
    - name: Set up Python 3.10
      uses: actions/setup-python@v5.4.0
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Test with Pytest & Playwright
      run: pytest
      env:
        BASE_URL_API: ${{ secrets.BASE_URL_API }}
        BASE_URL_UI: ${{ secrets.BASE_URL_UI }}
        DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD }}
        DEFAULT_USER: ${{ secrets.DEFAULT_USER }}
